name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      REGION: asia-southeast1
      PROJECT: ant-app-473121
      REPO: main
      IMAGE: ant-app
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GC_IMAGE_MANAGER_KEY }}
          project_id: ${{ env.PROJECT }}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker build -t $IMAGE:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE:latest asia-southeast1-docker.pkg.dev/$PROJECT/main/$IMAGE:latest
          docker tag $IMAGE:latest asia-southeast1-docker.pkg.dev/$PROJECT/main/$IMAGE:$GIT_TAG
          docker push asia-southeast1-docker.pkg.dev/$PROJECT/main/$IMAGE:latest
          docker push asia-southeast1-docker.pkg.dev/$PROJECT/main/$IMAGE:$GIT_TAG
