name: Build and Deploy to Google Cloud Run

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ant-app-473121 # Your GCP project ID
      REGION: asia-southeast1
      APP_NAME: ant # Your app name
      MEMORY: 2Gi
      CPU: 2
      IMAGE: ant-app # Docker image name
      REPO: ant-repo # Artifact Registry repo name (must exist)

    steps:
      # 1. Checkout the repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Create .env file from secrets
      - name: Create .env file
        run: |
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env

      # 3. Setup Google Cloud SDK and authenticate
      - name: Setup GCloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GC_IMAGE_MANAGER_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      # 4. Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      # 5. Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE }}:latest .

      # 6. Tag Docker image for Artifact Registry
      - name: Tag Docker Image
        run: |
          docker tag ${{ env.IMAGE }}:latest ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:latest
          docker tag ${{ env.IMAGE }}:latest ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:v0.1.0

      # 7. Push Docker image to Artifact Registry
      - name: Push Docker Image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:latest
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:v0.1.0

      # 8. Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.APP_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.IMAGE }}:latest \
            --platform managed \
            --region ${{ env.REGION }} \
            --memory ${{ env.MEMORY }} \
            --cpu ${{ env.CPU }} \
            --allow-unauthenticated
