name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      REGION: asia-southeast1
      PROJECT: ant-app-473121
      REPO: main
      IMAGE: ant-app
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GC_IMAGE_MANAGER_KEY }}
          project_id: ${{ env.PROJECT }}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker build -t $IMAGE:latest .

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Push Docker Image to Container Registry (GCR)
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE:latest gcr.io/$PROJECT/$IMAGE:latest
          docker tag $IMAGE:latest gcr.io/$PROJECT/$IMAGE:$GIT_TAG
          docker push gcr.io/$PROJECT/$IMAGE:latest
          docker push gcr.io/$PROJECT/$IMAGE:$GIT_TAG

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE:latest asia-southeast1-docker.pkg.dev/$PROJECT/main/$IMAGE:latest
          docker tag $IMAGE:latest asia-southeast1-docker.pkg.dev/$PROJECT/main/$IMAGE:$GIT_TAG
          docker push asia-southeast1-docker.pkg.dev/$PROJECT/main/$IMAGE:latest
          docker push asia-southeast1-docker.pkg.dev/$PROJECT/main/$IMAGE:$GIT_TAG
